version: 2.32.1.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - openssl
skip_tags: true
os: Visual Studio 2015
shallow_clone: true
clone_depth: 1

environment:
  MSYS2_PATH_TYPE: inherit
  CHERE_INVOKING: enabled_from_arguments
  matrix:
  - MSYSTEM: MINGW64
    MSYS_PACKAGES: mingw-w64-x86_64-boost mingw-w64-x86_64-miniupnpc
    MSYS_BITNESS: 64
  - MSYSTEM: MINGW32
    MSYS_PACKAGES: mingw-w64-i686-boost mingw-w64-i686-miniupnpc
    MSYS_BITNESS: 32

install:
- c:\msys64\usr\bin\bash -lc "pacman --noconfirm -Rns gcc-fortran gcc mingw-w64-{i686,x86_64}-gcc-ada mingw-w64-{i686,x86_64}-gcc-objc"
# TODO: revert that change when appveyor's images will be updated
- c:\msys64\usr\bin\bash -l "build/appveyor-msys2-upgrade.bash"
# update runtime
- c:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syuu"
# update packages and install required
- c:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syuu ${MSYS_PACKAGES}"

build_script:
- echo MSYSTEM = %MSYSTEM%, bitness = %MSYS_BITNESS%
- c:\msys64\usr\bin\bash -lc "make USE_UPNP=yes -j3"
- 7z a -tzip -mx9 -mmt i2pd-mingw-win%MSYS_BITNESS%.zip i2pd.exe

test: off

artifacts:
- path: i2pd-mingw-win*.zip
